name: Test smoke k6
on: [push]
permissions:
  contents: write
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: scripts/tests_smoke.js
      
      - run: ls & mkdir report & mv report_smoke.html report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report smoke
          path: report
      - name: publish report
        uses: peaceiris/actions-gh-pages@v3
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: report smoke
      